# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_name', models.CharField(max_length=200)),
                ('bed_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.CharField(max_length=254)),
                ('category', models.CharField(
                    choices=[('double', 'DOUBLE'), ('single', 'SINGLE'), ('double_decker', 'DOUBLE DECKER')],
                    default='single', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carpenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpenter_name', models.CharField(max_length=100)),
                ('carpenter_email', models.EmailField(max_length=254)),
                ('carpenter_password', models.CharField(max_length=100)),
                ('carpenter_tel_no', models.CharField(max_length=100)),
                ('carpenter_address', models.CharField(max_length=100)),
                ('carpenter_salary', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_password', models.CharField(max_length=100)),
                ('customer_tel_no', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('customer_class',
                 models.CharField(choices=[('Gold', 'GOLD'), ('Silver', 'SILVER')], default='Silver', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('material_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=100)),
                ('order_complete', models.BooleanField(default=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('order_completion_date', models.DateField()),
                ('carpenter',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Carpenter')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(max_length=200)),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.CharField(max_length=254)),
                ('category', models.CharField(
                    choices=[('Arm Chair', 'DOUBLE'), ('Classroom Chairs', 'Classroom Chairs'),
                             ('Office Chairs', 'Office Chairs'), ('Benches', 'Benches')], default='Office Chairs',
                    max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200)),
                ('table_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.CharField(max_length=254)),
                ('category', models.CharField(
                    choices=[('Coffee Table', 'Coffee Table'), ('Dinning Table', 'Dinning Table'),
                             ('Kitchen Table', 'Kitchen Table'), ('Office Table', 'Office Table')],
                    default='Coffee Table', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TempCarpenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_carpenter_name', models.CharField(max_length=100)),
                ('carpenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Carpenter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=250)),
                ('lent', models.BooleanField(default=False)),
                ('temp_carpenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='accounts.TempCarpenter')),
            ],
        ),
    ]
