# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='bed_name',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_password',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='image',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_name',
        ),
        migrations.AddField(
            model_name='carpenter',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='lending_rate_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.CharField(
                choices=[('nails', 'nails'), ('varnish', 'varnish'), ('glass', 'glass'), ('fabrics', 'fabrics'),
                         ('cushions', 'cushions')], default='nails', max_length=100),
        ),
        migrations.AlterField(
            model_name='seat',
            name='category',
            field=models.CharField(choices=[('Arm Chair', 'Arm Chair'), ('Classroom Chairs', 'Classroom Chairs'),
                                            ('Office Chairs', 'Office Chairs'), ('Benches', 'Benches')],
                                   default='Office Chairs', max_length=50),
        ),
    ]
