# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('accounts', '0002_auto_20170214_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('carpenter_tel_no', models.CharField(max_length=100)),
                ('carpenter_address', models.CharField(max_length=100)),
                ('carpenter_salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carpenter',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='temp_carpenter',
        ),
        migrations.RemoveField(
            model_name='tempcarpenter',
            name='carpenter',
        ),
        migrations.RemoveField(
            model_name='tempcarpenter',
            name='order',
        ),
        migrations.AddField(
            model_name='tempcarpenter',
            name='temp_carpenter_email',
            field=models.EmailField(default='carpenterA@fp.com', max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Carpenter',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
