# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20170216_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='carpenter',
        ),
    ]
