# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20170220_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_complete',
            new_name='complete_status',
        ),
    ]
