# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170220_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='payment_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
