# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderpayment_payment_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='payment_percentage',
        ),
    ]
