# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderpayment_payment_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='storage_fee',
            field=models.FloatField(default=0),
        ),
    ]
