# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170301_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='deposit',
            field=models.FloatField(),
        ),
    ]
