# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20170302_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='after_completion_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='storage_fee',
            field=models.FloatField(default=5000.0),
        ),
    ]
