# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20170302_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='storage_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
