# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderpayment_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='delivery_or_collection_date',
            field=models.DateField(null=True),
        ),
    ]
