# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_orderpayment_days_in_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='after_completion_days',
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='days_in_store',
            field=models.IntegerField(default=0),
        ),
    ]
