# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='furniture_category',
            field=models.CharField(choices=[('bed', 'Beds'), ('seat', 'Seats'), ('table', 'Tables')], default='Choose', max_length=200),
        ),
    ]
