# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170217_0240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='furniture',
            name='material_price',
            field=models.DecimalField(decimal_places=2, default=7500, max_digits=7),
            preserve_default=False,
        ),
    ]
