# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170220_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='lending_rate_per_day',
            field=models.FloatField(),
        ),
    ]
