# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_lenttool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='damage_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lenttool',
            name='damage_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lenttool',
            name='lending_fee',
            field=models.FloatField(default=0.0),
        ),
    ]
