# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170302_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenttool',
            name='damage_fee',
        ),
    ]
