# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_lenttool_damage_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenttool',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lenttool',
            name='was_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
