# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20170302_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenttool',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
