# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_auto_20170223_0911'),
        ('catalog', '0005_auto_20170220_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='LentTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(null=True)),
                ('lending_fee', models.FloatField()),
                ('damage_fee', models.FloatField(null=True)),
                ('temp_carpenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TempCarpenter')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tool')),
            ],
        ),
    ]
